<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ page import = "java.sql.*" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Database SQL Load</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database SQL Load</h2>
        <%
            /* How to customize:
             * 1. Update the database name on dbname.
             * 2. Create the list of tables, under tablenames[].
             * 3. Create the list of table definition, under tables[].
             * 4. Create the data into the above table, under data[]. 
             * 
             * If there is any problem, it will exit at the very first error.
             */
            String dbname = "sob_grup_08";
            String schema = "ROOT";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            /* this will generate database if not exist */
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname, "root", "root");
            Statement stmt = con.createStatement();
            
            /* inserting data */
            /* you have to exclude the id autogenerated from the list of columns if you have use it. */
            String data[] = new String[]{              
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'sob', 'sob')",
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, '1234', 'miriamduran')",
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'password', 'satxa')",
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'supersecurepassword', 'marcprofe')",
                
                "INSERT INTO " + schema + ".CUSTOMER VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'a@gmail.com', 'rey.jpg', 'sob', 'sob', 1)",
                "INSERT INTO " + schema + ".CUSTOMER VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'b@gmail.com', 'princesa.jpeg', 'Miriam', 'Duran', 2)",
                "INSERT INTO " + schema + ".CUSTOMER VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'c@gmail.com', 'fin.jpg', 'Satxa', 'Fortuny', 3)",
                "INSERT INTO " + schema + ".CUSTOMER VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'd@gmail.com', 'jake.jpg', 'Marc', 'Guifre', 4)",  
                
                "INSERT INTO " + schema + ".ARTICLE (id, content, featuredimageurl, ispublic, publishdate, resume, title, views, author_id) VALUES (NEXT VALUE FOR ARTICLE_GEN, "
                    + "'In recent years, **MIPS** (Microprocessor without Interlocked Pipeline Stages) has taken a significant"
                    + " share of the microprocessor market. Its architecture, known for efficiency and simplicity in design, has"
                    + " attracted major manufacturers. The adoption of MIPS in embedded devices, automotive systems, and IoT "
                    + "technology has surged due to its low power consumption and high performance. Competition with other "
                    + "architectures has been fierce, but MIPS has solidified its position thanks to its flexibility and scalability. "
                    + "More and more companies are choosing this architecture, securing its dominant position in the global tech market.'"
                    + ", 'foto1.png', 1, '2024-01-20', 'MIPS has absolutely demolished all the other types of processors inadvertently', "
                    + "'MIPS takes over the market', 0, 1)",
                
                "INSERT INTO " + schema + ".ARTICLE (id, content, featuredimageurl, ispublic, publishdate, resume, title, views, author_id) VALUES (NEXT VALUE FOR ARTICLE_GEN, "
                   + "'By leveraging machine learning algorithms, AI systems can analyze vast amounts of data to identify "
                    + "patterns, make predictions, and automate decision-making. This capability is transforming how "
                    + "businesses operate, offering personalized customer experiences, enhancing efficiency, and enabling "
                    + "smarter, data-driven choices. In recent years, advancements in deep learning and natural language "
                    + "processing have propelled AI to new heights, making it integral to everyday life. As AI continues "
                    + "to evolve, ethical considerations around privacy, bias, and transparency are becoming increasingly "
                    + "important, shaping the future development and deployment of intelligent systems.'"
                    + ", 'foto2.png', 1, '2024-02-20', 'IA has been advancing without stop, lets make a quick recap about it', "
                    + "'Artificial Intelligence (AI) is revolutionizing industries worldwide, from healthcare to finance.', 0, 1)",
               
                "INSERT INTO " + schema + ".ARTICLE (id, content, featuredimageurl, ispublic, publishdate, resume, title, views, author_id) VALUES (NEXT VALUE FOR ARTICLE_GEN, "
                    + "'Software is the backbone of modern technology, driving everything from personal devices to complex "
                    + "enterprise systems. It includes applications, operating systems, and frameworks that enable computers "
                    + "to perform specific tasks. The software industry is constantly evolving, with agile development and "
                    + "DevOps methodologies speeding up production and deployment. Open-source software has also grown in "
                    + "popularity, allowing communities to collaborate and innovate freely. Cloud computing has shifted how "
                    + "software is distributed, with services being delivered over the internet rather than installed locally. "
                    + "This evolution continues to push boundaries, making software a critical component of technological progress.'"
                    + ", 'foto3.png', 1, '2024-02-20', 'In today world we hear a lot about software but, what is it exactly?', "
                    + "'Small bites about software', 0, 1)",
                
                "INSERT INTO " + schema + ".ARTICLE (id, content, featuredimageurl, ispublic, publishdate, resume, title, views, author_id) VALUES (NEXT VALUE FOR ARTICLE_GEN, "
                    + "'Cybersecurity is crucial in a digital age where data breaches and cyber-attacks are constant threats. "
                    + "Protecting information, systems, and networks from unauthorized access requires a multifaceted approach, "
                    + "including firewalls, encryption, and robust authentication. As hackers become more sophisticated, the demand "
                    + "for skilled cybersecurity professionals grows. Companies are investing heavily in defensive strategies, from "
                    + "intrusion detection systems to threat intelligence platforms. The rise of remote work has also highlighted "
                    + "vulnerabilities, making cybersecurity more important than ever. Educating users and implementing security "
                    + "best practices are essential steps to safeguard sensitive information and maintain digital trust.'"
                    + ", 'foto4.png', 1, '2024-03-20', 'CyberSecurity is one of the most important things in our society', "
                    + "'CyberSecuritys importance', 0, 3)",
                
                "INSERT INTO " + schema + ".ARTICLE (id, content, featuredimageurl, ispublic, publishdate, resume, title, views, author_id) VALUES (NEXT VALUE FOR ARTICLE_GEN, "
                    + "'Data structures are fundamental elements in computer science, enabling efficient data organization and "
                    + "manipulation. Common data structures like arrays, linked lists, stacks, and queues provide the foundation "
                    + "for managing information. More advanced structures, such as trees, graphs, and hash tables, allow for "
                    + "complex operations, like searching, sorting, and pathfinding. Choosing the right data structure for a "
                    + "specific task can significantly impact the performance and efficiency of algorithms. As software "
                    + "development grows more complex, understanding data structures is essential for creating optimized, "
                    + "high-performance applications that can handle large datasets and demanding computations.'"
                    + ", 'foto5.png', 1, '2024-04-20', 'Data Structures are what enables us to make complex programs, dont be shy and click!', "
                    + "'What are Data Structures used for?', 0, 3)",
                
                "INSERT INTO " + schema + ".ARTICLE (id, content, featuredimageurl, ispublic, publishdate, resume, title, views, author_id) VALUES (NEXT VALUE FOR ARTICLE_GEN, "
                    + "'Hello I am Marc Sanchez and here I will make a quick explanation on how I got to see the "
                    + "infamous John Doe. It was a rainy day and I didnt want to move from the couch but I ran out"
                    + " of chocolate and I couldnt hande it. So I had to sacrifice my comodity to go buy some. When I was in"
                    + "the line to pay for my full truck of chocolate I encountered John Doe there. It turns out that he has"
                    + " an addiction to lobsters and was planning to but a whole truck too. I have to say that he was a pretty"
                    + " chill guy. From that day on we live together and we have 25 kids and a dog. The dog name is Federico.'"
                    + ", 'foto6.png', 0, '2024-04-20', 'Here I reveal all my personal secrets', "
                    + "'My secret confesions', 0, 4)",
                              
                "INSERT INTO " + schema + ".ARTICLE_TOPICS (article_id, topics) VALUES (1, 'Hardware')",
                "INSERT INTO " + schema + ".ARTICLE_TOPICS (article_id, topics) VALUES (2, 'AI')",
                "INSERT INTO " + schema + ".ARTICLE_TOPICS (article_id, topics) VALUES (2, 'Software')",
                "INSERT INTO " + schema + ".ARTICLE_TOPICS (article_id, topics) VALUES (3, 'Software')",
                "INSERT INTO " + schema + ".ARTICLE_TOPICS (article_id, topics) VALUES (4, 'Software')",
                "INSERT INTO " + schema + ".ARTICLE_TOPICS (article_id, topics) VALUES (4, 'CyberSecurity')",
                "INSERT INTO " + schema + ".ARTICLE_TOPICS (article_id, topics) VALUES (5, 'Software')",
                "INSERT INTO " + schema + ".ARTICLE_TOPICS (article_id, topics) VALUES (5, 'DataStructures')"
                    
              
             
            };
            for (String datum : data) {
                if (stmt.executeUpdate(datum)<=0) {
                    out.println("<span class='error'>Error inserting data: " + datum + "</span>");
                    return;
                }
                out.println("<pre> -> " + datum + "<pre>");
            }
        %>
        <button onclick="window.location='<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>
